### ISSUE TITLE
Wrong hompage link at "Hugo Themes"

### ISSUE THREAD

**Issue by yeongjukang** [knadh/hugo-ink#1]
Hi. 
From the this page, https://themes.gohugo.io/hugo-ink/
your homepage link has URL, https://github.com/knadh/ink, which returns 404.
I think it should be modified but don't know how to modify the link correctly.
So I am just letting you know.

Thank you for the good theme! :)

**Comment by knadh** [comment]
Thanks! Fixed https://github.com/knadh/hugo-ink/commit/fcaa4a2ada2f8b0b0549bfe6133a298de8c30da0
