### ISSUE TITLE
Markdown isn't rendered in post previews on the homepage

### ISSUE THREAD

**Issue by lossycache** [knadh/hugo-ink#22]
It'd be great if we can render markdown in previews of posts on the homepage, so we don't get raw markdown showing up on the homepage like so
<img width="826" alt="Screen Shot 2020-08-23 at 1 34 40 PM" src="https://user-images.githubusercontent.com/12592200/90988179-d4910780-e545-11ea-8c63-94418b7dba84.png">
If you change the `.RawContent` to `.Content` directives in `layouts/index.html` like so 
```
<span class="description">
	{{ if isset .Params "description" }}
		{{ .Description }}
	{{ else if gt (len .RawContent) 120 }}
		{{ slicestr .Content 0 120 }}...
	{{ else }}
		{{ .Content }}
	{{ end }}
</span>
```
The content renders with the HTML elements, which isn't exactly ideal either
<img width="772" alt="Screen Shot 2020-08-23 at 1 48 09 PM" src="https://user-images.githubusercontent.com/12592200/90988391-49b10c80-e547-11ea-967c-1d4598100df1.png">

Thanks for creating this beautiful theme!

**Comment by knadh** [comment]
If you have the `description` field set in your posts, it'll render Markdown if I remember correctly. Otherwise, the first 120 chars are automatically sliced from the body, where it's not possible to render Markdown (because it'd be partial content).

**Comment by lossycache** [comment]
Gotcha, I'll use the description field then. Thank you!
