### ISSUE TITLE
Error: File static/images/air_quality.png not found in resource path

### ISSUE THREAD

**Issue by learning-monk** [knadh/hugo-ink#28]
I saved an image at the path `./static/static/images/air_quality.png`. When I am adding this image to my R Markdown file, I keep getting this message `(No image at path static/images/air_quality.png)`.

<img width="901" alt="R markdown_question" src="https://user-images.githubusercontent.com/54142882/94694191-310bf180-0352-11eb-8818-29be46582070.PNG">

**Comment by knadh** [comment]
@vividvilla could you please take a look?

**Comment by vividvilla** [comment]
What is the path you specified in the markdown file? If your actual path is `./static/static/images/air_quality.png` then your markdown should be something like below

```
![image alt text](/static/images/air_quality.png)
```

Check Hugo docs for more details - https://gohugo.io/content-management/static-files/

**Comment by learning-monk** [comment]
Actual path: ./static/static/images/air_quality.png
Path in markdown file: ![image alt text](/static/images/air_quality.png)

[image: image.png]

**Comment by learning-monk** [comment]
Kailash/Vivek,

I found where the issue was. This pandoc markdown syntax is not working in
the R Markdown file for some reason which I need to investigate.

When I tried ![image alt text](/static/images/air_quality.png) in a
markdown file, it worked.

As soon as I find a fix, I will let you know.

Thank you so much for your help with this.

Regards,
Pratibha.

**Comment by learning-monk** [comment]
Kailash/Vivek,

Here is the fix.

*R Markdown code chunk:*

```{r air-quality, echo=FALSE, out.width = '100%'}
knitr::include_graphics("/static/images/air_quality.png", error = FALSE)
```

error=FALSE is important. If omitted, will result in 'file not found error'.


Regards,
Pratibha.

**Comment by knadh** [comment]
Thanks for documenting the fix here @learning-monk
