### ISSUE TITLE
If no date is specified, the current year should be used for the copyright year

### ISSUE THREAD

**Issue by Zambito1** [knadh/hugo-ink#29]
I removed the date field from my about page, since I didn't want a date to render near the title. When the field is removed however, the year used for the copyright in the footer is 1. I think using the current year (at the time the site is being generated) is ideal in this case.

**Comment by knadh** [comment]
https://github.com/knadh/hugo-ink/commit/ec4572d88ecadfd6fc733cab23b067d2008e2b83 fixes this.

**Comment by alexlawrence** [comment]
Sorry for beating the dead horse here. From what I've understood, the copyright year should be the year of the first publication. Alternatively, there can be a range of years starting with the year of first publication and ending with the year of last modification.

Would it be possible to change the template back to being configurable and use the current year only as fallback value?
