### ISSUE TITLE
Feature: Display Author and Tag list in post list

### ISSUE THREAD

**Issue by rajmahendra** [knadh/hugo-ink#32]
It will look good if we display Author and Tag in each item in the Post list

**Logic**
Author: If the author is provided on a page, display when it's listed in the post list, if not we can omit it
Tags: list all the stages for the page.

**Where to display?**
After header and subheading one more line and display both.

**Comment by knadh** [comment]
Hi @rajmahendra,
Ink's meant to be a single-author personal website theme. Don't think it makes sense to add the author meta per post. You could always fork and make these personalisations yourself, which is how the theme is intended to be used.
