### ISSUE TITLE
Header breaks when no subtitle is set

### ISSUE THREAD

**Issue by carstenhag** [knadh/hugo-ink#38]
Here I haven't specified a subtitle, but I did specify a menu and social links. The margins aren't right and the hover effects look sorta bad.

![image](https://user-images.githubusercontent.com/3776997/104105968-6198eb00-52b2-11eb-8311-0a416b0dc13b.png)

**Comment by knadh** [comment]
Fixed this https://github.com/knadh/hugo-ink/commit/3a50589e7a54f4c06e3381340e9681a5de887a81

Thanks for reporting.

**Comment by carstenhag** [comment]
Thanks :)
