### ISSUE TITLE
Sorta long-ish title cut off on mobile view

### ISSUE THREAD

**Issue by carstenhag** [knadh/hugo-ink#39]
Visit mampfen.chagemann.de, it's broken there. On chagemann.de it's displaying fine as it's only one line there. 

![Screenshot_20210120-190109](https://user-images.githubusercontent.com/3776997/105227372-7fdbd200-5b61-11eb-9050-21b9a3b6c5c5.jpg)

**Comment by knadh** [comment]
https://github.com/knadh/hugo-ink/commit/720096beb09f37c38a50da7c03dc2a8af2da6443 fixes this.

**Comment by carstenhag** [comment]
Thanks, it's fixed now :)
