### ISSUE TITLE
Fix page margins on iPad

### ISSUE THREAD

**Issue by ajeetdsouza** [knadh/hugo-ink#4]
Websites using the Ink theme have zero margins when viewed on an iPad.

To reproduce, go to the [demo website](https://themes.gohugo.io//theme/hugo-ink/) and switch devices from DevTools.

**Comment by knadh** [comment]
https://github.com/knadh/hugo-ink/commit/a9c79b493bcbcecd06ac5fc52433ee76dbf5e3f6 fixes this.
