### ISSUE TITLE
Request: Add thumbnail shortcut to post overview (start page)

### ISSUE THREAD

**Issue by carstenhag** [knadh/hugo-ink#41]
I want to use this theme for a sort of food blog for products and recipes. In the posts themselves I can add images. But in the post overview, the user doesn't see any type of visual guide as on what to expect.

Some quick mockups:

**Current design**
![Bildschirmfoto 2021-01-20 um 21 02 21](https://user-images.githubusercontent.com/3776997/105228369-ced63700-5b62-11eb-8219-126f901050b6.png)

----

**Thumbnail in place of the date/year**
![Bildschirmfoto 2021-01-20 um 21 01 15](https://user-images.githubusercontent.com/3776997/105228351-c5e56580-5b62-11eb-9146-2b8da471e225.png)

---

**Thumbnail in addition to the date/year**
![Bildschirmfoto 2021-01-20 um 21 01 37](https://user-images.githubusercontent.com/3776997/105228355-c7af2900-5b62-11eb-9d9c-4cc914e7d0ca.png)

**Comment by knadh** [comment]
You can easily customize this by using Hugo's [thumbnail features](https://blog.jeremylikness.com/blog/create-article-preview-in-hugo/). This needn't be added to Ink as it serves as a base for users to use and customize.
