### ISSUE TITLE
Switch code syntax highlight with dark or light mode

### ISSUE THREAD

**Issue by trebaud** [knadh/hugo-ink#43]
I would like to be able to switch colorschemes when switching from dark mode to light mode.
For example when in light mode we would have:
```
pygmentsStyle = "monokailight"
```

and in dark mode:
```
pygmentsStyle = "monokai"
```
Don't know if this is already possible.
Thank you!

**Comment by knadh** [comment]
Not familiar with this, but looks like Hugo can generate a syntax highlighting CSS file for a theme. https://gohugo.io/content-management/syntax-highlighting/

You could generate two such CSS files, one for light and one for dark, and load them on the frontend based on the light/dark selection.

**Comment by trebaud** [comment]
Oh perfect thanks!
