### ISSUE TITLE
Can't use year 2021

### ISSUE THREAD

**Issue by Rizwan-Hasan** [knadh/hugo-ink#44]
When I put the year 2021 on any post's date, it's updating.

**Comment by carstenhag** [comment]
What do you mean by "it's updating"? It work fine for me, see https://mampfen.chagemann.de/. What you need to take a look at
are these command line options for `hugo`:

```
  -D, --buildDrafts                include content marked as draft
  -E, --buildExpired               include expired content
  -F, --buildFuture                include content with publishdate in the future 
```

My guess is that you had dated the post in the future, and hugo did not build it. So you need to execute `hugo --buildFuture` for it to show up.

**Comment by Rizwan-Hasan** [comment]
Thanks 😊, I will check it out. Maybe the buildFuture is needed.
