### ISSUE TITLE
Post snippet render special characters

### ISSUE THREAD

**Issue by 0xtf** [knadh/hugo-ink#52]
Hi, I was wondering if anyone is having problem with the snippet of text in the post listing page where words such as `couldn't` can't properly be parsed and end up showing as `couldn&rsquo;t`.

**Comment by tarasmatsyk** [comment]
That's how planify works, 
```
		<span class="description">
			{{ if isset .Params "description" }}
				{{ .Description }}
			{{ else if gt (countrunes (.Content | plainify)) 120 }}
				{{ slicestr (.Content | plainify) 0 120 }}...
			{{ else }}
				{{ .Content | plainify }}
			{{ end }}
		</span>
```


not sure what's a proper way. For it was easier to set proper description in the post

PS: 🤙

**Comment by 0xtf** [comment]
@knadh any idea on how this could possibly be fixed?

**Comment by 0xtf** [comment]
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/24301448/147840951-33a4615a-aa16-4c48-abe9-65280e1d2d22.png">

**Comment by knadh** [comment]
@0xtf apologies for the delayed response, and thanks for finding the fix. It's added to the repo now.
