### ISSUE TITLE
Want to know the source of the articles in the demo

### ISSUE THREAD

**Issue by Sharelter** [knadh/hugo-ink#55]
I was inspired by two articles in the demo and wanna know the origin source of these to get further information.

The two articles are [this](https://hugo-ink.netlify.app/posts/post-2/) and [this](https://hugo-ink.netlify.app/posts/post-1/).

Sorry to disturb you ;)

**Comment by knadh** [comment]
The examples were forked from https://github.com/vividvilla/ezhil 

@vividvilla do you remember?

**Comment by vividvilla** [comment]
Its taken from - https://zenhabits.net for demo site. 
Contents are on public domain - https://zenhabits.net/uncopyright/

**Comment by Sharelter** [comment]
**THX** for generous help! Problem Solved
