### ISSUE TITLE
The elements including abbr, sub, sup, kbd and mark are invalid in the latest repository

### ISSUE THREAD

**Issue by zijeric** [knadh/hugo-ink#58]
The elements including abbr, sub, sup, kbd are invalid in the latest post article in latest repository. These elements are defined in normalize.css. However, sub element is valid in tag page.

**Comment by knadh** [comment]
Hi @A1va. Sorry, could you elaborate a bit and link to the exact file you're referring to?

**Comment by zijeric** [comment]
Hello @knadh.
Of course. It happens in the file content/posts/post-8.md.
Here's the situation.
After I cloned the latest commit from the main branch and set it to the blog theme in the config.toml file, I tried to check if it worked well on all posts. However, The Examples under the secondary heading "Other Elements - abbr, sub, sup, kbd, mark" in post-8.md are invalid. 
Thank you!

**Comment by knadh** [comment]
https://hugo-ink.netlify.app/posts/post-8/

Renders fine here. What version of Hugo are you using? Hugo regularly has changes that break silently between versions, unfortunately.

**Comment by A1va** [comment]
That's make sense. So Which Hugo version do you recommend? Below is the environment I'm using currently.
My platform: MacBook arm64
Hugo version: hugo v0.108.0+extended darwin/arm64 BuildDate=unknown.

**Comment by zijeric** [comment]
I have solved it! Thank you, your answer let me realize that is the question on Hugo.
It's the same question in [Hugo issue#7139](https://github.com/gohugoio/hugo/issues/7139)
When I put this into config.toml, then all the elements work.
```toml
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
```
> See https://gohugo.io/news/0.60.0-relnotes/.
