### ISSUE TITLE
The theme is currently not very useable for Europeans (GDPR)

### ISSUE THREAD

**Issue by dataCobra** [knadh/hugo-ink#8]
The GDPR makes it very difficult for bloggers to use third-party sites on there websites.
It would be great to change the following things:

 - [ ] Don't use the fonts via third-party site, use the fonts local instead
 - [ ] Instead of feathercdn which is also third-party, use a local font like FontAwesome
 - [ ] It should be possible to disable any other third-party function, as is the case with Disqus

That are some points that I was thinking about lately. Maybe there is some more todo, but this
is all I can remember now.

**Comment by dataCobra** [comment]
I will try to get some pull requests in for you to review. Maybe you have also some ideas how to accomplish this changes. :slightly_smiling_face:

**Comment by knadh** [comment]
Ah, yes!

I guess we can bundle the assets and have a `use_cdn=true|false` param in config that switches out CDN / local URLs in header.html
